version: '3'
services:
  audio-to-text:
    build: ./audio_to_text
    ports:
      - "5001:5001"

  text-to-audio:
    build: ./text_to_audio
    ports:
      - "5002:5002"

  generate-response:
    build: ./generate_response
    ports:
      - "5003:5003"

  select-animation:
    build: ./select_animation
    ports:
      - "5004:5004"

  main-orchestrator:
    build: ./main_orchestrator
    ports:
      - "5000:5000"
    depends_on:
      - audio-to-text
      - text-to-audio
      - generate-response
      - select-animation